database:
  host: "127.0.0.1"
  port: 5432
  username: "admin"
  password: "12345"
  name: "gamestats"
  ssl_mode: "disable"

kafka:
  host: "localhost"
  port: 9092
  player_events_topic: "player_events"

redis:
  host: "localhost"
  port: 6379
  db: 0

game_settings:
  kill_points: 1
  death_penalty: -1  